### PR TITLE
Fix compilation issue & new features for license summary, improved notice messages, copyrights and more... 

### PR DESCRIPTION
**Pull request by sergehuber**
This dummy text file is just there to force the creation of the test-repo directory otherwise the tests will fail.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Use a .donotdel instead?

**Comment by sergehuber** [comment]
Sure or another solution would be to force the creation of the directory in the test code if it doesn't exist.

**Comment by sergehuber** [comment]
I've added more features in my fork, here's the description : 

New features:
- Add #GENERATE_LICENSE_SUMMARY# to NOTICE template to generate a summary of all the licenses encountered. New licenseSummaryMessage parameter to control it. For example :

License summary:

#GENERATED_LICENSE_SUMMARY#

will generate something like this :

License summary:

1. Apache (1 occurences)
2. Apache License (2 occurences)
3. Apache Public License 2.0 (1 occurences)
4. Apache Software License 2.0 (1 occurences)
5. Apache Software Licenses (1 occurences)
6. Bouncy Castle Licence (2 occurences)
7. BSD (4 occurences)
8. BSD 3-Clause (6 occurences)
9. BSD licence (2 occurences)
10. CDDL + GPLv2 with classpath exception (1 occurences)

These license summaries also have a new settings : licenseSummaryMessage with a default value of : {0}. {1} ({2} occurences)
where:
{0} - index in the list
{1} - license name
{2} - occurences of the license

- More control over the message strings. It is now possible to use newline characters (\n) to have more control over the message generation for notice message, copyright messages, or license summary messages. For example:
<noticeMessage>\nThis product includes the software {0}.\nLicensed under the {1}.\n{7}</noticeMessage>

- More parameters are available in the notice message, here's the full list :
{0} - artifact name
{1} - license name
if the project information is available you will also have the following additional parameters
{2} - groupId
{3} - artifactId
{4} - version
{5} - organization name
{6} - organization url
{7} - copyright message
Example, using this : <noticeMessage>\nThis product includes the software {0}.\nLicensed under the {1}.\n{7}</noticeMessage>
Will produce the following :

This product includes the software OPS4J Base - Execution.
Licensed under the The Apache Software License, Version 2.0.
Copyright (C) 2006-2015 OPS4J - Open Participation Software for Java (http://www.ops4j.org/)

- License name aliases. It is often the case that projects use different wording for the same license. Now it is possible to define aliases to avoid
having different names in the NOTICE file. Example:

                            <licenseNameAliases>
                                <property>
                                    <name>Apache License, Version 2.0</name>
                                    <value>The Apache Software License, Version 2.0</value>
                                </property>
                                <property>
                                    <name>Apache 2</name>
                                    <value>The Apache Software License, Version 2.0</value>
                                </property>
                                <property>
                                    <name>ALv2</name>
                                    <value>The Apache Software License, Version 2.0</value>
                                </property>
                                <property>
                                    <name>Apache 2.0 License</name>
                                    <value>The Apache Software License, Version 2.0</value>
                                </property>
                                <property>
                                    <name>Apache License 2.0</name>
                                    <value>The Apache Software License, Version 2.0</value>
                                </property>
                                <property>
                                    <name>Apache License Version 2.0</name>
                                    <value>The Apache Software License, Version 2.0</value>
                                </property>
                            </licenseNameAliases>

I hope these will be interesting to you because it would be great to have them in the main project.

**Comment by sergehuber** [comment]
Renamed the dummy.txt file to .donotdel

**Comment by sergehuber** [comment]
I would love to get feedback on these changes, and possibly see how I can help in getting them merged as I have want to use these improvements in multiple projects. Let me know how I can help ?

**Comment by mmoayyed** [comment]
I think the only project under the Jasig foundation that uses this plugin is uPortal. (and even uPortal is moving towards Gradle in the future) So for the time being, you may want to either ping @apetro , @drewwills, @jameswennmacher or @timlevett and see whether they are able to help you. 

...or completely fork the repo as I suspect this project may be retiring soon. But that is just my guess.

**Comment by sergehuber** [comment]
Well I have forked it already, and indeed if the plan is to retire it I will maintain my own fork. 

Btw are you saying that uPortal will be moving this functionality to Gradle ?

**Comment by mmoayyed** [comment]
Don't know. I suspect they will drop it but I am not affiliated with the project anymore.

**Comment by cvgaviao** [comment]
@sergehuber Great improvements ! do you have a snapshot published anywhere?

**Comment by apetro** [comment]
Hi @sergehuber . I don't see an Apereo ICLA on file in your name. Cf. https://github.com/Jasig/maven-notice-plugin/pull/7/files . ICLA would help smooth accepting contributions.

**Comment by ChristianMurphy** [comment]
@sergehuber uPortal has transitioned to Gradle as the build system.
It is likely that uPortal will look to move to a Gradle based plugin at some point.

**Comment by ChristianMurphy** [comment]
Hey @sergehuber, thanks for the pull request!
Unfortunately are merge conflicts that have cropped up that are blocking these changes from being merged.
I'm going to close this PR, feel free to re-open it if you have time to resolve the merge conflicts.

**Pull request closed without merging**
